
# Global
url: http://presesequences.com

# Build options
markdown: kramdown
permalink: date
# Schrift template configuration
# ------------------------------

# For META headers
author: Andrew Miller
description: Musings about designing and making things


title: (pre)sequences  # Appears in the window title of the browser. Stands alone on the homepage, sits beside the post title on post pages.
# Enter below the headtitle of your weblog/website
#    | It appears on the main navigation bar. You can use <span></span> to nicely fade out some part of it
maintitle: (pre)sequences

# Enter below a short description that will sit next to your head title. (keep it short)
#    | {optional}
# maindesc: <a href=https://github.com/Schoewilliam/Schrift><span class=oi data-glyph=fork></span> Fork me</a>

# https://useiconic.com/open for icon reference
menus:
- text: Archive
  url: /archive
  openiconic: list
- text: Some Page
  url: /2015/01/25/lorem-ipsum.html
  openiconic: list-rich
- text: an About page
  url: /about.html
  openiconic: info

# Enter an invitation message
#    | It lies right beneath every post to invite your readers to react and comment
#    | {optional}
#invitationmsg: If you have any feedback you would like me to read, please don't hesitate to send them over to <a href=mailto:you@domain.xyz>you@domain.xyz</a>.
